In [2]:
import pandas as pd
import regex as re
from cleantext import clean
import pyarrow.feather as feather
from multiprocessing import Pool
import gc
import nltk
import itertools
import numpy as np
from nltk.corpus import stopwords
from nltk.stem.porter import *
import time
from collections import Counter
from sklearn.model_selection import train_test_split    # splitting the data

In [3]:
import pandas as pd
import regex as re
from cleantext import clean
data = pd.read_csv('https://raw.githubusercontent.com/several27/FakeNewsCorpus/master/news_sample.csv', dtype={"content": "string"})
data.head()

Unnamed: 0   id                domain        type  \
0           0  141               awm.com  unreliable   
1           1  256     beforeitsnews.com        fake   
2           2  700           cnnnext.com  unreliable   
3           3  768               awm.com  unreliable   
4           4  791  bipartisanreport.com   clickbait   

                                                 url  \
0  http://awm.com/church-congregation-brings-gift...   
1  http://beforeitsnews.com/awakening-start-here/...   
2  http://www.cnnnext.com/video/18526/never-hike-...   
3  http://awm.com/elusive-alien-of-the-sea-caught...   
4  http://bipartisanreport.com/2018/01/21/trumps-...   

                                             content  \
0  Sometimes the power of Christmas will make you...   
1  AWAKENING OF 12 STRANDS of DNA – “Reconnecting...   
2  Never Hike Alone: A Friday the 13th Fan Film U...   
3  When a rare shark was caught, scientists were ...   
4  Donald Trump has the unnerving ability to abil...   

                   scraped_at                 inserted_at  \
0  2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
1  2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
2  2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
3  2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
4  2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   

                   updated_at  \
0  2018-02-02 01:19:41.756664   
1  2018-02-02 01:19:41.756664   
2  2018-02-02 01:19:41.756664   
3  2018-02-02 01:19:41.756664   
4  2018-02-02 01:19:41.756664   

                                               title          authors  \
0  Church Congregation Brings Gift to Waitresses ...      Ruth Harris   
1  AWAKENING OF 12 STRANDS of DNA – “Reconnecting...     Zurich Times   
2  Never Hike Alone - A Friday the 13th Fan Film ...              NaN   
3  Elusive ‘Alien Of The Sea ‘ Caught By Scientis...  Alexander Smith   
4  Trump’s Genius Poll Is Complete & The Results ...  Gloria Christie   

   keywords meta_keywords                                   meta_description  \
0       NaN          ['']                                                NaN   
1       NaN          ['']                                                NaN   
2       NaN          ['']  Never Hike Alone: A Friday the 13th Fan Film  ...   
3       NaN          ['']                                                NaN   
4       NaN          ['']                                                NaN   

  tags  summary  
0  NaN      NaN  
1  NaN      NaN  
2  NaN      NaN  
3  NaN      NaN  
4  NaN      NaN

In [4]:
# remove everything with null type
data = data[data['type'].isnull() == False]

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(tokenizer=lambda x : x)
X = vectorizer.fit_transform(data['content'])
y = data['type']

/Users/mikkelkjaerulf/miniconda3/envs/fake_news/lib/python3.10/site-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [6]:
X_train, X_val, y_train, y_val = train_test_split(X, data['type'], test_size=0.2, random_state=0)
X_val, X_test, y_val, y_test = train_test_split(X_val, y_val, test_size=0.5, random_state=0)

In [7]:
print(X_train.toarray())

[[ 182 3689    4 ...    0    0    0]
 [  22  128    3 ...    0    0    0]
 [  40  569    0 ...    0    0    0]
 ...
 [  58 1167    2 ...    0    0    0]
 [  48 1275    6 ...    0    0    0]
 [   0  601    0 ...    0    0    0]]


In [8]:
print(X_train.toarray().shape)

(190, 105)


In [9]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train.toarray(), y_train)

MultinomialNB()

In [10]:
pred = model.predict(X_val)

In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, pred)

0.7916666666666666